In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 30.2 ms


In [3]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 2.53 s


In [4]:
data = np.random.randn(2,3)

In [5]:
data

array([[ 1.81042379,  0.97181481, -0.16634769],
       [-0.86536597,  0.81778062,  0.80225703]])

In [12]:
data*10

array([[18.10423787,  9.71814811, -1.66347692],
       [-8.65365972,  8.17780616,  8.02257029]])

In [7]:
data+data

array([[ 3.62084757,  1.94362962, -0.33269538],
       [-1.73073194,  1.63556123,  1.60451406]])

In [8]:
data.shape


#  차원의 크기를 알려주는 Shape라는 튜플

(2, 3)

In [9]:
data.dtype


# 자료형을 알려주는 dtype라는 객체

dtype('float64')

In [10]:
data1 = [6,7.5, 8, 0, 1]
arr1 = np.array(data1)

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim


#배열의 차원 수 or 배열의 축 수

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [26]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
arr.dtype

dtype('int32')

In [31]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [32]:
float_arr

array([1., 2., 3., 4., 5.])

In [33]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [34]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [35]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)

In [36]:
numeric_strings.astype(float)


#np.float64 형태로 입력하여도 무방

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)

In [38]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [40]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
empty_uint32 = np.empty(8, dtype='u4')

In [43]:
empty_uint32

# empty는 초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성

# 주의해야 할 것은 메모리도 초기화되지 않기 때문에 예상하지 못한 쓰레기 값이 들어가 있음.

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [44]:
arr = np.array([[1., 2., 3.,],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
arr**0.5
# **은 거듭제곱 연산자

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

In [51]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [52]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [53]:
arr = np.arange(10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5]

5

In [56]:
arr[5:8]

array([5, 6, 7])

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr_slice = arr[5:8]
arr_slice 

array([5, 6, 7])

In [59]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [60]:
arr_slice

array([    5, 12345,     7])

In [61]:
arr_slice[:] = 64


# : 배열의 모든값을 할당

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

In [66]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
old_values = arr3d[0].copy()

In [69]:
arr3d[0] = 42

In [70]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[1,0]

array([7, 8, 9])

In [73]:
x = arr3d[1]

In [74]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [75]:
x[0]

array([7, 8, 9])

In [76]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [77]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [81]:
arr2d[1, :2]

array([4, 5])

In [82]:
arr2d[:2, 2]

array([3, 6])

In [83]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [84]:
arr2d[:2, 1:] = 0

In [85]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [86]:
names = np.array(['Bob',"Joe",'Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [87]:
data

array([[ 0.04514074, -1.17620028,  0.88329813,  0.5631872 ],
       [-0.03647711,  1.28885978, -1.26944682, -0.96003946],
       [ 0.39433729, -0.38978923,  1.46751775,  0.28165474],
       [ 1.06238761, -0.04613722, -0.0814708 , -1.41228356],
       [-0.10639692,  0.16969104, -0.52117991, -0.41773908],
       [-0.60777208, -0.48998533, -0.99065747,  0.27451448],
       [ 0.23592207, -1.83018133,  1.29025897,  0.55301089]])

In [88]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [89]:
data[names == 'Joe']

array([[-0.03647711,  1.28885978, -1.26944682, -0.96003946],
       [-0.60777208, -0.48998533, -0.99065747,  0.27451448],
       [ 0.23592207, -1.83018133,  1.29025897,  0.55301089]])

In [90]:
data[names == 'Bob', 2:]

array([[ 0.88329813,  0.5631872 ],
       [-0.0814708 , -1.41228356]])

In [91]:
data[names == 'Bob', 3]

array([ 0.5631872 , -1.41228356])

In [92]:
names != 'Bob'


#  != 부정 (집합기호로~의 의미와 동)

array([False,  True,  True, False,  True,  True,  True])

In [93]:
data[~(names == 'Bob')]

array([[-0.03647711,  1.28885978, -1.26944682, -0.96003946],
       [ 0.39433729, -0.38978923,  1.46751775,  0.28165474],
       [-0.10639692,  0.16969104, -0.52117991, -0.41773908],
       [-0.60777208, -0.48998533, -0.99065747,  0.27451448],
       [ 0.23592207, -1.83018133,  1.29025897,  0.55301089]])

In [94]:
cond = names == 'Bob'

In [95]:
data[~cond]

array([[-0.03647711,  1.28885978, -1.26944682, -0.96003946],
       [ 0.39433729, -0.38978923,  1.46751775,  0.28165474],
       [-0.10639692,  0.16969104, -0.52117991, -0.41773908],
       [-0.60777208, -0.48998533, -0.99065747,  0.27451448],
       [ 0.23592207, -1.83018133,  1.29025897,  0.55301089]])

In [96]:
mask = (names == 'Bob')|(names == 'Will')


#두가지 이상을 사용하고싶을경우 &(and) 나 |(or)과 같은 논리 연산자 사용

In [97]:
mask

array([ True, False,  True,  True,  True, False, False])

In [98]:
data[data<0] = 0

In [99]:
data

array([[0.04514074, 0.        , 0.88329813, 0.5631872 ],
       [0.        , 1.28885978, 0.        , 0.        ],
       [0.39433729, 0.        , 1.46751775, 0.28165474],
       [1.06238761, 0.        , 0.        , 0.        ],
       [0.        , 0.16969104, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.27451448],
       [0.23592207, 0.        , 1.29025897, 0.55301089]])

In [100]:
arr = np.empty((8,4))

In [101]:
for i in range(8):
    arr[i] = i

In [102]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [103]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [104]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [105]:
arr = np.arange(32).reshape((8,4))

In [106]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [108]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [109]:
arr = np.arange(15).reshape(3,5)

In [110]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [111]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [112]:
arr = np.random.randn(6,3)

In [113]:
arr

array([[ 0.22897518, -0.7513708 , -0.14851097],
       [-1.29802605, -0.12995245,  0.15999586],
       [-0.58807511, -0.97262668, -1.13578419],
       [ 0.41522266,  2.212916  , -0.10717729],
       [ 0.00599579, -0.06934206, -1.15827058],
       [-0.65425119, -0.94926842, -0.27693969]])

In [114]:
np.dot(arr.T, arr)


#행렬의 내적 (크게 다루지는 않을 듯..ㅇㅅㅇ..)

array([[2.68362401, 2.10811104, 0.55598323],
       [2.10811104, 7.33036445, 1.30152158],
       [0.55598323, 1.30152158, 2.7674332 ]])

In [115]:
arr= np.arange(16).reshape((2,2,4))

In [116]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [117]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [118]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [119]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.sqrt(arr)


# sqrt :제곱근

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [121]:
np.exp(arr)


# 자연상수e에 대한 arr원소들의 제곱

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [122]:
x = np.random.randn(8)
y = np.random.randn(8)

In [123]:
x

array([-0.79693546,  1.30382659, -0.71988652, -0.21667575,  1.33011914,
        1.97673027, -0.0858114 ,  1.43345334])

In [124]:
y

array([-1.59023674,  0.79604143, -0.26517667,  0.28437481, -0.92274153,
       -0.27945208,  1.02731625, -0.69888493])

In [125]:
np.maximum(x,y)

array([-0.79693546,  1.30382659, -0.26517667,  0.28437481,  1.33011914,
        1.97673027,  1.02731625,  1.43345334])

In [126]:
arr = np.random.randn(7)*5
arr

array([ 3.25089872,  0.59783532,  4.62551109, -0.34664981, 10.51577124,
       10.30412422,  6.03097198])

In [127]:
remainder,whole_part = np.modf(arr)
remainder

array([ 0.25089872,  0.59783532,  0.62551109, -0.34664981,  0.51577124,
        0.30412422,  0.03097198])

In [128]:
whole_part

array([ 3.,  0.,  4., -0., 10., 10.,  6.])

In [129]:
arr

array([ 3.25089872,  0.59783532,  4.62551109, -0.34664981, 10.51577124,
       10.30412422,  6.03097198])

In [130]:
np.sqrt(arr)

<ipython-input-130-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.80302488, 0.77319811, 2.15070014,        nan, 3.24280299,
       3.21000377, 2.45580373])

In [131]:
np.sqrt(arr,arr)

<ipython-input-131-e3ca18b15869>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([1.80302488, 0.77319811, 2.15070014,        nan, 3.24280299,
       3.21000377, 2.45580373])

In [132]:
arr

array([1.80302488, 0.77319811, 2.15070014,        nan, 3.24280299,
       3.21000377, 2.45580373])